### ISSUE TITLE
Error when running flutter pub get after adding fonoApi

### ISSUE THREAD

**Issue by thearthurdev** [ThinkDigitalSoftware/fonoapi-dart#1]
I'm tring to import this package into my project but I keep getting this error whenever I run flutter pub get

"Because every version of flutter_test from sdk depends on meta 1.1.7 and fonoapi_dart >=0.1.2+2 depends on meta ^1.1.8, flutter_test from sdk is incompatible with fonoapi_dart >=0.1.2+2.

So, because playgrnd depends on both fonoapi_dart ^0.1.2+2 and flutter_test any from sdk, version solving failed.
pub get failed (1)
exit code 1"

**Comment by ThinkDigitalSoftware** [comment]
Give me a sec.

**Comment by ThinkDigitalSoftware** [comment]
Published a new version 0.1.3

**Comment by thearthurdev** [comment]
Wow, impressed by the quick response. I'll give it a go and get back to you. Thanks!

**Comment by ThinkDigitalSoftware** [comment]
You're welcome! I haven't tested it since it's in your code, but let me know. if it doesn't show up in pub soon enough, use the git repo

**Comment by thearthurdev** [comment]
Flutter pub get was successful! Thanks!

**Comment by ThinkDigitalSoftware** [comment]
Welcome!
